---
- name: Build Bluetooth receiver
  hosts: raspberrypi
  become: yes
  remote_user: pi

  vars:
    a2dp_class: "0x20041C"
  tasks:
  - name: install dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
    with_items:
    - pulseaudio
    - pulseaudio-module-bluetooth
    - pulsemixer
  - name: configure bluetooth audio
    template:
      src: bluetooth-main.conf.j2
      dest: /etc/bluetooth/main.conf
